### PR TITLE
Feature/UI redesign

### PR DESCRIPTION
**Pull request by seth-nelson**
## Description ##

This is a small bugfix where some components of the groomer dashboard have been updated to match the general UI layout for the rest of the app. This includes changing mostly text and button colors and styles. This PR is ready for a final review.

## Type ##

- [x] This is a bugfix.
- [ ] This is a new feature.
- [x] This is part of a feature.

## Organization ##

- [x] Have you linked this pull request to a Trello card?
- [x] Have you named the branch in the format of feature/describe_feature_or_change OR bug/describe_bug_this_is_fixing 

## Review ##

- [ ] Is this a work in progress?
- [x] Is this ready to be reviewed?
- [x] Have you added two reviewers to this pull request?

### CODE REVIEW

**Comment by seth-nelson** [comment]
I will fix the merge conflict. I pulled from main, but maybe this was not incorporated in my pull.

**Review by Aaron-Mendez2001 — DISMISSED** [review]
Looking good, good catch! There might still be a conflict though it looks like

**Comment by seth-nelson** [comment]
Yes, it looks like when I updated the PR from main, the Calendar.js file is now throwing an error code. I'll see if I can fix it.

**Comment by Caleno83** [comment]
Yes, it looks that is a conflict in the Twilio Form

**Comment by seth-nelson** [comment]
Ok, I just fixed it. Sorry about that. Not sure why it didn't pull the few changes from before.

**Comment by seth-nelson** [comment]
When I pulled from main, for some reason, the Calendar.js file is throwing a build and check error. Looks like there is commented code in the file saying that it's throwing commit errors. I dismissed it for now because I'm not sure if Evelyn is still fixing it or not. Thoughts?

**Review by Caleno83 — APPROVED** [review]
Yes, its because the useContext for the Appointment.  Thanks it looks good!

**Review by Aaron-Mendez2001 — APPROVED** [review]
Looks good here!

**Pull request merged**
