### PR TITLE
removed the $500 bonus on the third section of the landing page due t…

### PR DESCRIPTION
**Pull request by seth-nelson**
…o the component and feature not being built yet.

## Description ##

This PR removes the information about the $500 bonus. This feature is not implemented yet, so I removed it due to it not being relevant at this time in the product cycle.

## Type ##

- [x] This is a bugfix.
- [ ] This is a new feature.
- [ ] This is part of a feature.

## Organization ##

- [x] Have you linked this pull request to a Trello card?
- [x] Have you named the branch in the format of feature/describe_feature_or_change OR bug/describe_bug_this_is_fixing 

## Review ##

- [ ] Is this a work in progress?
- [x] Is this ready to be reviewed?
- [x] Have you added two reviewers to this pull request?

### CODE REVIEW

**Review by jeffglanville — APPROVED** [review]

**Comment by jeffglanville** [comment]
Looks Great per the code. Not able to view due to state error

**Comment by seth-nelson** [comment]
I will look into this today Jeff, thank you for the heads up.

**Review by kimboyd12 — APPROVED** [review]
Looks good!

**Review by Caleno83 — APPROVED** [review]
It looks pretty good! The code is well formatted, and easy to understand.

**Pull request merged**
